name: marvel_characters
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  equatable: ^2.0.5
  crypto: ^3.0.3
  go_router: ^11.1.2
  get_it: ^7.6.4
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1

  mobx: ^2.2.0
  flutter_mobx: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.6
  
  test: ^1.24.3
  mocktail: ^1.0.1
  faker: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
